project_id = "iulcagiivxneyayvfuzw"

[functions.upload-document]
verify_jwt = false

[functions.submit-registration]
verify_jwt = false

[functions.fetch-registrations]
verify_jwt = false

[functions.update-registration]
verify_jwt = false

[functions.delete-registration]
verify_jwt = false
